update=Fri 08 Sep 2017 10:05:38 AM PET
version=1
last_client=kicad
[general]
version=1
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill="    0,000000"
PadDrillOvalY="    0,000000"
PadSizeH="    1,500000"
PadSizeV="    3,000000"
PcbTextSizeV="    1,000000"
PcbTextSizeH="    1,000000"
PcbTextThickness="    0,300000"
ModuleTextSizeV="    1,000000"
ModuleTextSizeH="    1,000000"
ModuleTextSizeThickness="    0,150000"
SolderMaskClearance="    0,000000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,200000"
BoardOutlineThickness="    0,150000"
ModuleOutlineThickness="    0,150000"
[pcbnew/libraries]
LibName1=/home/mcotera/Devel/lib/KiCad/mcotera/modules/varius_MC
LibName2=/home/mcotera/Devel/lib/KiCad/walter/modules/w_capacitors
LibName3=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_9159
LibName4=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_d-sub
LibName5=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_kk156
LibName6=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_misc
LibName7=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_mkds
LibName8=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_mpt
LibName9=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_pc
LibName10=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_pt-1,5
LibName11=/home/mcotera/Devel/lib/KiCad/walter/modules/w_conn_strip
LibName12=/home/mcotera/Devel/lib/KiCad/walter/modules/w_crystal
LibName13=/home/mcotera/Devel/lib/KiCad/walter/modules/w_details
LibName14=/home/mcotera/Devel/lib/KiCad/walter/modules/w_indicators
LibName15=/home/mcotera/Devel/lib/KiCad/walter/modules/w_logo
LibName16=/home/mcotera/Devel/lib/KiCad/walter/modules/w_pin_strip
LibName17=/home/mcotera/Devel/lib/KiCad/walter/modules/w_pth_circuits
LibName18=/home/mcotera/Devel/lib/KiCad/walter/modules/w_pth_diodes
LibName19=/home/mcotera/Devel/lib/KiCad/walter/modules/w_pth_resistors
LibName20=/home/mcotera/Devel/lib/KiCad/walter/modules/w_relay
LibName21=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_cap
LibName22=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_dil
LibName23=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_diode
LibName24=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_inductors
LibName25=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_leds
LibName26=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_lqfp
LibName27=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_resistors
LibName28=/home/mcotera/Devel/lib/KiCad/walter/modules/w_smd_trans
LibName29=/home/mcotera/Devel/lib/KiCad/walter/modules/w_switch
LibName30=/home/mcotera/Devel/lib/KiCad/walter/modules/w_to
LibName31=sockets
LibName32=connect
LibName33=discret
LibName34=pin_array
LibName35=divers
LibName36=smd_capacitors
LibName37=smd_resistors
LibName38=smd_crystal&oscillator
LibName39=smd_dil
LibName40=smd_transistors
LibName41=libcms
LibName42=display
LibName43=led
LibName44=dip_sockets
LibName45=pga_sockets
LibName46=valves
LibDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=usbasp-rescue
LibName2=/home/mcotera/Devel/lib/KiCad/mcotera/library/switch_MC
LibName3=/home/mcotera/Devel/lib/KiCad/walter/library/power
LibName4=/home/mcotera/Devel/lib/KiCad/walter/library/w_analog
LibName5=/home/mcotera/Devel/lib/KiCad/walter/library/w_connectors
LibName6=/home/mcotera/Devel/lib/KiCad/walter/library/w_device
LibName7=/home/mcotera/Devel/lib/KiCad/walter/library/w_logic
LibName8=/home/mcotera/Devel/lib/KiCad/walter/library/w_microcontrollers
LibName9=/home/mcotera/Devel/lib/KiCad/walter/library/w_opto
LibName10=/home/mcotera/Devel/lib/KiCad/walter/library/w_relay
LibName11=power
LibName12=device
LibName13=transistors
LibName14=conn
LibName15=linear
LibName16=regul
LibName17=74xx
LibName18=cmos4000
LibName19=adc-dac
LibName20=memory
LibName21=xilinx
LibName22=special
LibName23=microcontrollers
LibName24=dsp
LibName25=microchip
LibName26=analog_switches
LibName27=motorola
LibName28=texas
LibName29=intel
LibName30=audio
LibName31=interface
LibName32=digital-audio
LibName33=philips
LibName34=display
LibName35=cypress
LibName36=siliconi
LibName37=opto
LibName38=atmel
LibName39=contrib
LibName40=valves
